version: "3.8"
services:
  docker:
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-cache:/var/lib/docker
    networks: [jenkins]
    hostname: docker
    command: ["--host=tcp://0.0.0.0:2376","--host=unix:///var/run/docker.sock"]

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: "root"
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks: [jenkins]
    depends_on: [docker]

networks:
  jenkins:

volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:
  docker-cache:
